# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: ubuntu
#   pool: 5
#   timeout: 5000

#Per the platform...
development:
  adapter: postgresql
  encoding: unicode
  database: ninja_gold_development
  pool: 5
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ninja_gold
  pool: 5
  username: ubuntu
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ninja_gold_production
  pool: 5
  username: ubuntu
  password:
